---
- name: Provision AWX Operator on kubernetes node
  hosts: control_node
  roles:
    - role: create_users
      vars:
        username: kadmin
  #  - role: install_k3s
  #  - role: install_awx_operator