---
- name: Provision AWX Operator on kubernetes node
  hosts: control_node
  vars:
    kubernetes_admin_user: kadmin
  roles:
    - role: create_users
      vars:
        username: "{{ kubernetes_admin_user }}"
    - role: provision_kubernetes
      vars:
        username: "{{ kubernetes_admin_user }}"
  #  - role: install_awx_operator